// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=interfaces_mock_test.go -package=formexample
//

// Package formexample is a generated GoMock package.
package formexample

import (
	context "context"
	http "net/http"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCSRFProtector is a mock of CSRFProtector interface.
type MockCSRFProtector struct {
	ctrl     *gomock.Controller
	recorder *MockCSRFProtectorMockRecorder
	isgomock struct{}
}

// MockCSRFProtectorMockRecorder is the mock recorder for MockCSRFProtector.
type MockCSRFProtectorMockRecorder struct {
	mock *MockCSRFProtector
}

// NewMockCSRFProtector creates a new mock instance.
func NewMockCSRFProtector(ctrl *gomock.Controller) *MockCSRFProtector {
	mock := &MockCSRFProtector{ctrl: ctrl}
	mock.recorder = &MockCSRFProtectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCSRFProtector) EXPECT() *MockCSRFProtectorMockRecorder {
	return m.recorder
}

// Token mocks base method.
func (m *MockCSRFProtector) Token(request *http.Request) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Token", request)
	ret0, _ := ret[0].(string)
	return ret0
}

// Token indicates an expected call of Token.
func (mr *MockCSRFProtectorMockRecorder) Token(request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Token", reflect.TypeOf((*MockCSRFProtector)(nil).Token), request)
}

// Valid mocks base method.
func (m *MockCSRFProtector) Valid(request *http.Request) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Valid", request)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Valid indicates an expected call of Valid.
func (mr *MockCSRFProtectorMockRecorder) Valid(request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Valid", reflect.TypeOf((*MockCSRFProtector)(nil).Valid), request)
}

// MockContactCreator is a mock of ContactCreator interface.
type MockContactCreator struct {
	ctrl     *gomock.Controller
	recorder *MockContactCreatorMockRecorder
	isgomock struct{}
}

// MockContactCreatorMockRecorder is the mock recorder for MockContactCreator.
type MockContactCreatorMockRecorder struct {
	mock *MockContactCreator
}

// NewMockContactCreator creates a new mock instance.
func NewMockContactCreator(ctrl *gomock.Controller) *MockContactCreator {
	mock := &MockContactCreator{ctrl: ctrl}
	mock.recorder = &MockContactCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContactCreator) EXPECT() *MockContactCreatorMockRecorder {
	return m.recorder
}

// CreateContact mocks base method.
func (m *MockContactCreator) CreateContact(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateContact", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateContact indicates an expected call of CreateContact.
func (mr *MockContactCreatorMockRecorder) CreateContact(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateContact", reflect.TypeOf((*MockContactCreator)(nil).CreateContact), ctx, name)
}
